In [4]:
import numpy as np
import torch

ModuleNotFoundError: No module named 'numpy'

In [3]:
a=np.array([[2,3,6,3,4],[3,5,7,8,10],[6,5,4,9,12]])
print(a)

[[ 2  3  6  3  4]
 [ 3  5  7  8 10]
 [ 6  5  4  9 12]]


In [4]:
tensor=torch.from_numpy(a)
print(tensor)

tensor([[ 2,  3,  6,  3,  4],
        [ 3,  5,  7,  8, 10],
        [ 6,  5,  4,  9, 12]])


In [8]:
result=tensor[:,1::2];
print(result)

tensor([[3, 3],
        [5, 8],
        [5, 9]])


In [11]:
b=np.array([[2,3,6,3,4],
           [3,5,7,8,10],
           [6,5,4,9,12]])
print(a)

[[ 2  3  6  3  4]
 [ 3  5  7  8 10]
 [ 6  5  4  9 12]]


In [32]:
tensor1=torch.from_numpy(b)
#print(tensor1)
result1=tensor1[-2::,-5:-2:2];
print(result1)

tensor([[3, 7],
        [6, 4]])


In [20]:
c=np.array([[2,3,6,3,4],
           [3,5,7,8,10],
           [6,5,4,9,12],
           [3,5,7,8,10]])
print(c)
tensor2=torch.from_numpy(c)
print(tensor2)

[[ 2  3  6  3  4]
 [ 3  5  7  8 10]
 [ 6  5  4  9 12]
 [ 3  5  7  8 10]]
tensor([[ 2,  3,  6,  3,  4],
        [ 3,  5,  7,  8, 10],
        [ 6,  5,  4,  9, 12],
        [ 3,  5,  7,  8, 10]])


In [30]:
rowsum = tensor2.sum(dim=1, keepdim=True)
pd= tensor2 / rowsum
print(pd)


tensor([[0.1111, 0.1667, 0.3333, 0.1667, 0.2222],
        [0.0909, 0.1515, 0.2121, 0.2424, 0.3030],
        [0.1667, 0.1389, 0.1111, 0.2500, 0.3333],
        [0.0909, 0.1515, 0.2121, 0.2424, 0.3030]])
