<div align="center">
<img src="https://drive.google.com/uc?id=1JOzNG8Sf9rXQ_nHqlzOvzOnpr4iSIkmc" width="250">

<img src="https://drive.google.com/uc?id=1SctzfeQJDdGN2eMRQhJEoQWWO9rovrWh" width="300">
</div>


## Numpy

[Numpy](https://numpy.org/) is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. To use Numpy, we first need to import the numpy package as `import numpy as np`


In [1]:
import numpy as np

### Arrays

A numpy array is a grid of values, **all of the same type**, and is indexed by a tuple of nonnegative integers. **The number of dimensions is the rank of the array**; the shape of an array is a tuple of integers giving the size of the array along each dimension. We can initialize numpy arrays from nested Python lists, and access elements using square brackets:


In [2]:
a = [1, 2, 3]
print(type(a))

<class 'list'>


In [3]:
a = np.array(a)  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 5                 # Change an element of the array
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [ ]:
b = np.array([
              [1, 2, 3],
              [4, 5, 6]
              ])   # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0])

(2, 3)
1 2 4


Numpy also provides many functions to create arrays:


In [13]:
a = np.zeros((4, 2))  # Create an array of all zeros
print(type(a))
a

<class 'numpy.ndarray'>


array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
b = np.ones((5, 3, 2), dtype=np.int32)   # Create an array of all ones
print(b)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


In [17]:
c = np.full((2,2), 9, dtype=np.float32) # Create a constant array
print(c)

[[9. 9.]
 [9. 9.]]


In [18]:
d = np.eye(2, dtype=np.int32)        # Create a 2x2 identity matrix
print(d)

[[1 0]
 [0 1]]


In [20]:
e = np.random.random((3,2))*10 # Create an array filled with random values
print(e)

[[9.15031535 9.10941223]
 [9.30307068 2.27765714]
 [7.46043811 6.6899857 ]]


In [21]:
# range(1, 11, 2)

ri = np.random.randint(1, 101, (2, 2, 4))
ri

array([[[18, 96, 23, 46],
        [43, 57,  8, 67]],

       [[49, 31, 25, 97],
        [94, 70, 36, 61]]])

### Datatypes

**Every numpy array is a grid of elements of the same type.** Numpy provides a large set of numeric datatypes that you can use to construct arrays. **Numpy tries to guess a datatype when you create an array**, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. Here is an example:

You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).


In [ ]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int32)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int64 float64 int32


In [24]:
x = np.array([1, 2.6], dtype=np.float32)
print(x.dtype)

float32


## Array math

**Basic mathematical functions operate elementwise on arrays**, and are available both as operator overloads and as functions in the numpy module:


In [25]:
x = np.array([[1,2],
              [3,4]]) # 2, 2
y = np.array([[5,6],
              [7,8]]) # 2, 2

# Elementwise sum; both produce the array
print(x + y)

[[ 6  8]
 [10 12]]


In [26]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))
print(np.add(x, y))

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]]
[[ 6  8]
 [10 12]]


In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
print(np.exp(x))

[[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]


## **Important Note**

`*` is elementwise multiplication, not matrix multiplication. **We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices.** dot is available both as a function in the numpy module and as an instance method of array objects:


In [28]:
x = np.array([[1,2],[3,4]]) # 2, 2
y = np.array([[5,6],[7,8]]) # 2, 2

v = np.array([9,10])  # 1, 2
# v = v.reshape(1, len(v))
w = np.array([11, 12]) # 1, 2
# w = w.reshape(1, len(w))

# Inner product of vectors; both produce 219
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [30]:
a = np.random.randint(1, 10, (3, 2))
b = np.random.randint(1, 10, (3, 2))
print(a)
print(b)

c = np.matmul(a, b.T)
print(c)

[[9 2]
 [3 1]
 [2 7]]
[[9 2]
 [4 3]
 [6 6]]
[[85 42 66]
 [29 15 24]
 [32 29 54]]


**You can also use the @ operator which is equivalent to numpy's dot operator.**


In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:


In [ ]:
x = np.array([[1,15],
              [3,10]])

print(np.sum(x) ) # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

29
[ 4 25]
[16 13]


You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:


In [ ]:
print(x)
print("transpose\n", x.transpose())

[[ 1 15]
 [ 3 10]]
transpose
 [[ 1  3]
 [15 10]]


In [31]:
y = np.array([[1, 2, 3], [2, 3, 4]])
print(y)
print(y.shape)
print(y.T)
print(y.T.shape)

[[1 2 3]
 [2 3 4]]
(2, 3)
[[1 2]
 [2 3]
 [3 4]]
(3, 2)


In [ ]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


In [ ]:
import numpy as np

# example of numpy array
x = np.array([1, 2, 3])
print(x)

[1 2 3]


If $x$ is a vector, then a Python operation such as $s = x + 3$ or $s = \frac{1}{x}$ will output s as a vector of the same size as x.


In [32]:
# example of vector operation
x = np.array([1, 2, 3])
print (x - 3)

[-2 -1  0]


In fact, if $ x = (x_1, x_2, ..., x_n)$ is a row vector then $np.exp(x)$ will apply the exponential function to every element of x. The output will thus be: $np.exp(x) = (e^{x_1}, e^{x_2}, ..., e^{x_n})$


In [ ]:
import numpy as np

# example of np.exp
x = np.array([1, 2, 3])
print(np.exp(x)) # result is (exp(1), exp(2), exp(3))

[ 2.71828183  7.3890561  20.08553692]


Any time you need more info on a numpy function, we encourage you to look at [the official documentation](https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.exp.html).


## What is Pytorch?

[PyTorch](https://pytorch.org/) is a python package built by **Facebook AI Research (FAIR)** that provides two high-level features:

- Tensor computation (like numpy) with strong GPU acceleration
- Deep Neural Networks built on a tape-based autograd (_Automatic Gradient Calculation_) system

## Why Pytorch?

- **More Pythonic**

  - Flexible
  - Intuitive and cleaner code
  - Easy to learn & debug
  - Dynamic Computation Graph (_network behavior can be changed programmatically at runtime_)

- **More Neural Networkic**
  - Write code as the network works
  - forward/backward


## Checking PyTorch version


In [33]:
import torch

print(torch.__version__)

2.5.1+cu121


## Introduction to Tensors

A **PyTorch Tensor** is basically the same as a numpy array: it does not know anything about deep learning or computational graphs or gradients, and is just a generic **n-dimensional array** to be used for arbitrary **numeric computation**.

The biggest difference between a numpy array and a PyTorch Tensor is that a **PyTorch Tensor can run on either CPU or GPU**. To run operations on the GPU, **just cast the Tensor to a cuda datatype**.

A scalar is **zero-order tensor** or rank zero tensor. A vector is a **one-dimensional** or first order tensor, and a matrix is a **two-dimensional** or second order tensor.

<div align="center">
<img src="https://drive.google.com/uc?id=1pka-LVyrq_7r0sCm59cvOQofEYAcnO4r" width="550">
</div>

<div align="center">
<img src="https://drive.google.com/uc?id=1zHT5CGzIgpe1aLkdawrllTMn74nYVeAp" width="550">
</div>


A [torch.Tensor](https://pytorch.org/docs/stable/tensors.html) is a **multi-dimensional matrix** containing elements of a **single data type**.

`torch.Tensor` is an alias for the default tensor type (`torch.FloatTensor`).


In [34]:
t = torch.tensor([[1, -1],
              [1, -1]])
print(type(t))

<class 'torch.Tensor'>


In [36]:
x = torch.rand([5, 3])
print(x)
print(type(x))

tensor([[0.6942, 0.4380, 0.2818],
        [0.8735, 0.5316, 0.3905],
        [0.2760, 0.1006, 0.0164],
        [0.1007, 0.9385, 0.2667],
        [0.7659, 0.9038, 0.8528]])
<class 'torch.Tensor'>


In [ ]:
torch.randint(1, 101, (2, 2))

tensor([[88, 79],
        [85, 19]])

In [37]:
torch.ones((2, 2), dtype=torch.int32)

tensor([[1, 1],
        [1, 1]], dtype=torch.int32)

In [ ]:
# Converting numpy arrays to tensors
import numpy as np

np_arr = np.array([[1, 2, 3], [4, 5, 6]])
torch.tensor(np_arr, dtype = torch.int)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [ ]:
# Converting numpy arrays to tensors
np_values = np.array([[1, 2, 3], [4, 5, 6]])

tensor_values = torch.from_numpy(np_values)

print (tensor_values)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# A tensor of specific data type can be constructed by passing a torch.dtype

torch.zeros([2, 4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [38]:
# The contents of a tensor can be accessed and modified using Python’s indexing and slicing notation:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x[1, 2].item())

# Modify a certain element
x[0][1] = 8
print(x)

6
tensor([[1, 8, 3],
        [4, 5, 6]])


In [ ]:
# Use torch.Tensor.item() to get a Python number from a tensor containing a single value

x = torch.tensor([[1]])
print(x)
y = x.item()
print(y)

x = torch.tensor(2.5)

print(x.item())

tensor([[1]])
1
2.5


In [ ]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x.size(), x.dim())

torch.Size([2, 3]) 2


In [ ]:
# Tensor addition & subtraction
x = torch.rand(5, 3)
y = torch.rand(5, 3)

print(x)
print(y)

print(x + y)
print(x - y)

tensor([[0.5445, 0.4829, 0.0500],
        [0.5041, 0.2484, 0.1334],
        [0.9111, 0.5114, 0.4576],
        [0.2124, 0.9864, 0.9823],
        [0.1282, 0.1967, 0.1598]])
tensor([[0.0570, 0.6666, 0.1002],
        [0.7154, 0.1136, 0.4125],
        [0.8662, 0.6773, 0.2961],
        [0.2297, 0.7646, 0.0949],
        [0.8040, 0.9974, 0.9384]])
tensor([[0.6014, 1.1495, 0.1502],
        [1.2194, 0.3620, 0.5458],
        [1.7774, 1.1887, 0.7537],
        [0.4421, 1.7510, 1.0772],
        [0.9322, 1.1940, 1.0982]])
tensor([[ 0.4875, -0.1836, -0.0502],
        [-0.2113,  0.1349, -0.2791],
        [ 0.0449, -0.1660,  0.1615],
        [-0.0173,  0.2218,  0.8874],
        [-0.6758, -0.8007, -0.7786]])


In [ ]:
# Syntax 2 for Tensor addition & subtraction in PyTorch
print(torch.add(x, y))
print(torch.sub(x, y))
print(x*y)
x.mul(y)

tensor([[0.6014, 1.1495, 0.1502],
        [1.2194, 0.3620, 0.5458],
        [1.7774, 1.1887, 0.7537],
        [0.4421, 1.7510, 1.0772],
        [0.9322, 1.1940, 1.0982]])
tensor([[ 0.4875, -0.1836, -0.0502],
        [-0.2113,  0.1349, -0.2791],
        [ 0.0449, -0.1660,  0.1615],
        [-0.0173,  0.2218,  0.8874],
        [-0.6758, -0.8007, -0.7786]])
tensor([[0.0310, 0.3219, 0.0050],
        [0.3606, 0.0282, 0.0550],
        [0.7892, 0.3464, 0.1355],
        [0.0488, 0.7542, 0.0932],
        [0.1031, 0.1961, 0.1500]])


tensor([[0.0310, 0.3219, 0.0050],
        [0.3606, 0.0282, 0.0550],
        [0.7892, 0.3464, 0.1355],
        [0.0488, 0.7542, 0.0932],
        [0.1031, 0.1961, 0.1500]])

In [ ]:
# Tensor Product & Transpose

mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 3)

print(mat1)
print(mat2)

print(torch.mm(mat1, mat2))

print(mat1.t())

tensor([[ 0.3946,  1.6107, -0.3049],
        [-1.0261,  1.0810, -0.7242]])
tensor([[-1.4522, -0.2233, -0.6757],
        [ 0.2209, -0.3746, -0.8616],
        [ 1.8219, -0.0672,  0.1828]])
tensor([[-0.7726, -0.6710, -1.7100],
        [ 0.4095, -0.1272, -0.3703]])
tensor([[ 0.3946, -1.0261],
        [ 1.6107,  1.0810],
        [-0.3049, -0.7242]])


In [39]:
# Elementwise multiplication
t = torch.Tensor([[1, 2], [3, 4]])
t.mm(t)

tensor([[ 7., 10.],
        [15., 22.]])

In [40]:
# Shape, dimensions, and datatype of a tensor object

x = torch.rand(5, 3)
print(x)

print('Tensor shape:', x.shape)   # t.size() gives the same
print('Number of dimensions:', x.dim())
print('Tensor type:', x.type())   # there are other types

tensor([[0.3801, 0.5787, 0.7226],
        [0.3961, 0.6596, 0.8560],
        [0.5133, 0.6881, 0.5307],
        [0.8835, 0.6011, 0.2178],
        [0.4085, 0.1360, 0.5893]])
Tensor shape: torch.Size([5, 3])
Number of dimensions: 2
Tensor type: torch.FloatTensor


In [46]:
# Slicing
t = torch.Tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [7, 8, 9]])

print(t[-3:-1, -2:-1])

tensor([[5.],
        [8.]])


In [ ]:
t = torch.Tensor([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])

t[0:2, 1:3]

tensor([[2., 3.],
        [5., 6.]])

In [ ]:
t[-3:-1, -2:]

tensor([[5., 6.],
        [8., 9.]])

In [47]:
x = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

In [49]:
x[-4::2, -3::2]


array([[1, 3],
       [7, 9]])